### ISSUE TITLE
Parser

### ISSUE THREAD

**Issue by JacobNickerson** [JacobNickerson/jbash#1]
Implement a more robust parser than just splitting on white space

**Comment by cbloodsworth** [comment]
The current lexer is a single function with a signature `String -> ArrayList<String>`. We can think of it as an intelligent string splitter. Here are some pieces I'd like to add before merging into main:

- [x] Do not split mid-quotation (`'` or `"` characters)
  - For string literals or formatted strings
- [x] Do not split mid-parentheses (`(` or `)` characters)
  - For sub-expressions
  - [x] Also have it so that `$(xxx)` is grabbed as a single string.
- [x] Do not split mid-curly brackets (`{` or `}` characters)
  - For ranges
  - [x] Also have it so `${xxx}` is grabbed as a single string.
    - For shell variables

**Comment by cbloodsworth** [comment]
Before I begin the work here, I may have to modify the signature of the lexer -- rather than returning an `ArrayList<String>`, it'd be nice to return `ArrayList<Token>` -- these tokens would likely be just a record like `Token(String lexeme, TokenType type)`, just so we have more information once we parse the tokens into some kind of tree.

This change would likely be committed directly to main, since it's a breaking change that I'd like to ensure we all have ASAP.

**Comment by cbloodsworth** [comment]
The parser is a lot more robust, but there are certain basic design decisions that is going to make POSIX-compliancy near impossible (i.e., order of operations on string evaluation.) Read [here](https://pubs.opengroup.org/onlinepubs/9699919799/) for more information on this. I am going to begin writing tests that ensure we stick as close to the standard as possible (we may deviate later, but as a starting point, we should keep as compliant as possible.)

**Comment by cbloodsworth** [comment]
Closing issue for now, too broad a scope. Will reopen with a narrower scope and more details.
